### ISSUE TITLE
When update Atom?

### ISSUE THREAD

**Issue by Lucien950** [purduesigbots/pros#311]
#### Actual Behavior:

I have some files, they don't play well with file file-icons/atom

#### Steps to reproduce:

Just boot up the app, and when it's loading, it throws one of these

### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /-\*-(?:[ \t]*(?=[^:;\s]+[ \t]*-\*-)|(?:.*?[ \t;]|(?<=-\*-))[ \t]*mode[ \t]*:[ \t]*)([^:;\s]+)(?=[ \t;]|(?<![-*])-\*-).*?-\*-/: Invalid group

```
At C:\Users\jessi\.pros-editor\packages\file-icons\lib\service\strategies\modeline-strategy.js:24

SyntaxError: Invalid regular expression: /-\*-(?:[ \t]*(?=[^:;\s]+[ \t]*-\*-)|(?:.*?[ \t;]|(?<=-\*-))[ \t]*mode[ \t]*:[ \t]*)([^:;\s]+)(?=[ \t;]|(?<![-*])-\*-).*?-\*-/: Invalid group
    at ModelineStrategy.matchIcon (/packages/file-icons/lib/service/strategies/modeline-strategy.js:24:21)
    at ModelineStrategy.check (/packages/file-icons/lib/service/strategy.js:134:22)
    at ModelineStrategy.check (/packages/file-icons/lib/service/strategies/header-strategy.js:52:16)
    at StrategyManager.query (/packages/file-icons/lib/service/strategy-manager.js:87:32)
    at Immediate.setImmediate (/packages/file-icons/lib/service/icon-delegate.js:243:38)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
busy 0.7.0 
busy-signal 2.0.1 
file-icons 2.1.47 
ide-cquery 0.14.0 
minimap 4.39.14 
minimap-cursorline 1.0.5 
minimap-find-and-replace 5.0.9 
minimap-selection 4.5.5 
pros-atom3 2.2.0 
terminal-tab-plus 0.5.11 
tool-bar 1.4.4 
tool-bar-main 0.0.12 
```

#### System information:
Platform: V5
PROS Kernel Version:
Name      Version    Origin
--------  ---------  -------------
kernel    3.5.2      pros-mainline
okapilib  4.2.0      pros-mainline

#### Screenshots/Output Dumps/Stack Traces
![image](https://user-images.githubusercontent.com/20777515/131253379-e1ec2da1-613f-490b-9e82-52aaa569ab8c.png)

**Comment by WillXuCodes** [comment]
Sometime when we get somebody who can prioritize this... this is the wrong repository for this anyways.
