### ISSUE TITLE
pros make giving python error

### ISSUE THREAD

**Issue by lolgeny** [purduesigbots/pros#313]
#### Expected Behavior:
I ran `pros make`, and expected a successful build.

#### Actual Behavior:
I got this output:
```
$ pros make
ERROR - __main__:main - [WinError 3] The system cannot find the path specified
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\subprocess.py", line 800, in __init__
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\subprocess.py", line 1207, in _execute_child
FileNotFoundError: [WinError 3] The system cannot find the path specified
We detected something went wrong! Do you want to send a report? [y/N]:
```
Additionally, no matter if I send a bug report or not it freezes the terminal and becomes unresponsive to ctrl-c, ctrl-d, and ctrl-z

#### Steps to reproduce:
- Make a new project
- `pros make` or `pros build`
Unfortunately I don't know more than that. I've built successfully on my machine before.

#### System information:
Platform: v5
PROS Kernel Version: 

#### Additional Information
Windows, pros 3.2.2. Other non-build cli commands seem to work.

#### Screenshots/Output Dumps/Stack Traces
`pros make --debug --verbose`
```
$ pros make --verbose --debug
INFO - pros.cli.common:callback - Debugging messages enabled
DEBUG - pros:callback - CLI Version: 3.2.2
INFO - pros.conductor.project:find_project - Found Project Path: C:\Users\me\Documents\coding\video\project.pros
INFO - pros.conductor.project:find_project - Found Project Path: C:\Users\me\Documents\coding\video\project.pros
DEBUG - pros.config.config:__init__ - Opening C:\Users\me\Documents\coding\video\project.pros (Project)
DEBUG - pros.config.config:__init__ - Opening C:\Users\me\AppData\Roaming\PROS\cli.pros (CliConfig)
ERROR - __main__:main - [WinError 3] The system cannot find the path specified
Traceback (most recent call last):
  File "pros/cli/main.py", line 47, in main
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\click\core.py", line 697, in main
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\click\core.py", line 1066, in invoke
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\click\core.py", line 895, in invoke
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\click\core.py", line 535, in invoke
  File "D:\a\1\s\pros\cli\build.py", line 23, in make
  File "D:\a\1\s\pros\conductor\project\__init__.py", line 386, in compile
  File "D:\a\1\s\pros\conductor\project\__init__.py", line 230, in make
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\sentry_sdk\integrations\stdlib.py", line 193, in sentry_patched_popen_init
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\subprocess.py", line 800, in __init__
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\subprocess.py", line 1207, in _execute_child
FileNotFoundError: [WinError 3] The system cannot find the path specified
We detected something went wrong! Do you want to send a report? [y/N]: 
```
(name changed to `me` for privacy reasons)

**Comment by Sleuth56** [comment]
This is a CLI issue not a pros issue. If someone could move this to github.com/purduesigbots/pros-cli that would be great.
