### ISSUE TITLE
pros flash gives TypeError on Arch

### ISSUE THREAD

**Issue by kfish610** [purduesigbots/pros#73]
#### Expected Behavior:
`pros flash` should flash the program
#### Actual Behavior:
```
pros flash
Traceback (most recent call last):
  File "/usr/bin/pros", line 11, in <module>
    load_entry_point('pros-cli==2.6.1', 'console_scripts', 'pros')()
  File "/usr/lib/python3.7/site-packages/proscli/main.py", line 9, in main
    cli.main(prog_name='pros')
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)

  File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
TypeError: flash() got an unexpected keyword argument 'file'
```
#### Steps to reproduce:
On my computer I just run pros flash in any folder
#### System information:
Operating System:  (Windows, OS X, Ubuntu)
`Arch Linux (Antergos)`
PROS Version: (run `pros --version`)
`pros, version 2.6.1`
#### Additional Information

`pros poll` and `pros lsusb` both work, so does every other function, including terminal, other than flash.
```
uname -a    
Linux klaptop 4.18.12-arch1-1-ARCH #1 SMP PREEMPT Thu Oct 4 01:01:27 UTC 2018 x86_64 GNU/Linux
```

**Comment by HotelCalifornia** [comment]
you already opened this issue at purduesigbots/pros-cli#63, which is the right place for such issues
